# Generated by Django 6.1 on 2026-08-25 10:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250, verbose_name="عنوان")),
                ("description", models.TextField(verbose_name="توضیحات")),
                ("slug", models.SlugField(max_length=250, verbose_name="اسلاگ")),
                (
                    "publish",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="تاریخ"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DR", "Draft"),
                            ("PB", "Published"),
                            ("RE", "Rejected"),
                        ],
                        default="DR",
                        max_length=2,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blog",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="نویسنده",
                    ),
                ),
            ],
            options={
                "verbose_name": "پست",
                "verbose_name_plural": "پست ها",
                "ordering": ["-publish"],
                "indexes": [
                    models.Index(
                        fields=["publish"], name="blog_post_publish_c4286e_idx"
                    )
                ],
            },
        ),
    ]
