# Generated by Django 6.1 on 2026-09-08 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_post_reading_time_alter_comment_active_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_file", models.ImageField(upload_to="post_images/")),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name="عنوان"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="blog.post",
                        verbose_name="پست",
                    ),
                ),
            ],
            options={
                "verbose_name": "تصویر",
                "verbose_name_plural": "تصویر ها",
                "ordering": ["created"],
                "indexes": [
                    models.Index(
                        fields=["created"], name="blog_image_created_1ba45b_idx"
                    )
                ],
            },
        ),
    ]
