# Generated by Django 6.1 on 2026-09-08 09:25

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image_file",
            field=django_resized.forms.ResizedImageField(
                crop=["middle", "center"],
                force_format=None,
                keep_meta=True,
                quality=75,
                scale=None,
                size=[500, 500],
                upload_to="post_images/",
            ),
        ),
    ]
