# Generated by Django 6.1 on 2026-09-15 15:47

import django.db.models.deletion
import django_resized.forms
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_alter_image_image_file"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(blank=True, null=True, verbose_name="تاریخ تولد"),
                ),
                ("bio", models.TextField(blank=True, null=True, verbose_name="بایو")),
                (
                    "photo",
                    django_resized.forms.ResizedImageField(
                        blank=True,
                        crop=["middle", "center"],
                        force_format=None,
                        keep_meta=True,
                        null=True,
                        quality=75,
                        scale=None,
                        size=[500, 500],
                        upload_to="account_images/",
                        verbose_name="تصویر",
                    ),
                ),
                (
                    "job",
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name="شغل"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "اکانت",
                "verbose_name_plural": "اکانت ها",
            },
        ),
    ]
