# Generated by Django 6.1 on 2026-09-15 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_account"),
    ]

    operations = [
        migrations.RenameField(
            model_name="account",
            old_name="date",
            new_name="date_of_birth",
        ),
    ]
