# Generated by Django 6.1 on 2026-09-18 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_rename_date_account_date_of_birth"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.CharField(
                choices=[
                    ("تکنولوژی", "تکنولوژی"),
                    ("زبان برنامه نویسی", "زبان برنامه نویسی"),
                    ("هوش مصنوعی", "هوش مصنوعی"),
                    ("بلاکچین", "بلاکچین"),
                    ("سایر", "سایر"),
                ],
                default="سایر",
                max_length=20,
            ),
        ),
    ]
